esphome:
  name: "${device_brand}-${device_model}-${device_mac_suffix}"
  friendly_name: "${device_friendly_name}"
captive_portal:
web_server:
logger:
  baud_rate: 0
api:
ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_brand}-${device_model}-${device_mac_suffix}"
    password: !secret wifi_fallback_password
sensor:
  - platform: uptime
    name: ${entity_name_prefix}Uptime Sensor
switch:
  - platform: restart
    name: "${device_friendly_name} Restart"